name: build and release

on:
  push

jobs:
  build-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install RTools
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install rtools --version=3.5 -y
      
      - name: Install R
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install r.project -y
      
      #- name: Install dependencies
        #run: "C:\\Program Files\\R\\R-3.6.1\\bin\\Rscript.exe" -e "1+1" 
        #run: "C:\\Program Files\\R\\R-3.6.1\\bin\\Rscript.exe" -e "install.packages(c('remotes', 'rcmdcheck', 'devtools', 'Rcpp'))" 
        #run: "C:\\Program Files\\R\\R-3.6.1\\bin\\Rscript.exe" -e "remotes::install_deps(dependencies = TRUE)"
      
      #- name: Build binary
      #  run: |
      #    "C:\Program Files\R\R-3.6.1\bin\Rscript.exe" -e "devtools::document(roclets = c('rd', 'collate', 'namespace', 'vignette'))"
      #    "C:\Program Files\R\R-3.6.1\bin\Rscript.exe" -e "devtools::build(binary = TRUE, args = c('--preclean'))"
      
      - name: test
        run: dir
